name: Continuous Integration

on:
  pull_request: ~
  push:
    branches: [master, alpha, greenkeeper/*]
    tags: ~

jobs:
  test:
    name: Build Package

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Packages
        run: npm install

      - name: Format Check
        run: npm run check

      - name: Build Library
        run: npm run build:prod

      - name: Unit Tests
        run: npm run test -- --coverage

      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup Docker for Cucumber Test
        run: docker-compose -f docker-compose.yml up -d

      - name: Sleep for 60 # we could do health checks here for better accuracy
        run: sleep 60

      - name: Cucumber Tests
        run: npm run cucumber -- --tags "not @stack"
        env:
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake
          AWS_ENDPOINT: http://localhost
          AWS_REGION: us-east-1
          S3_ENDPOINT: http://localhost:1080
          ON_EVENT_PORT: 9001
          ON_EVENT_S3_BUCKET_NAME: test-bucket
          ON_EVENT_S3_OBJECT_KEY: test-object-key
          ON_EVENT_INDEX: test-index
          ELASTICSEARCH_ENDPOINT: http://localhost:9200
          ELASTICSEARCH_INDEX: test-index

      - name: Semantic Release
        run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
